/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FLIGHT_COMMAND_PB_H_INCLUDED
#define PB_FLIGHT_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _FlightCommand_CommandType {
    FlightCommand_CommandType_COMMAND_NONE = 0,
    FlightCommand_CommandType_COMMAND_LAUNCH = 1,
    FlightCommand_CommandType_COMMAND_ABORT = 2
} FlightCommand_CommandType;

/* Struct definitions */
typedef struct _FlightCommand {
    FlightCommand_CommandType type;
} FlightCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _FlightCommand_CommandType_MIN FlightCommand_CommandType_COMMAND_NONE
#define _FlightCommand_CommandType_MAX FlightCommand_CommandType_COMMAND_ABORT
#define _FlightCommand_CommandType_ARRAYSIZE ((FlightCommand_CommandType)(FlightCommand_CommandType_COMMAND_ABORT+1))

#define FlightCommand_type_ENUMTYPE FlightCommand_CommandType


/* Initializer values for message structs */
#define FlightCommand_init_default               {_FlightCommand_CommandType_MIN}
#define FlightCommand_init_zero                  {_FlightCommand_CommandType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define FlightCommand_type_tag                   1

/* Struct field encoding specification for nanopb */
#define FlightCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1)
#define FlightCommand_CALLBACK NULL
#define FlightCommand_DEFAULT NULL

extern const pb_msgdesc_t FlightCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define FlightCommand_fields &FlightCommand_msg

/* Maximum encoded size of messages (where known) */
#define FLIGHT_COMMAND_PB_H_MAX_SIZE             FlightCommand_size
#define FlightCommand_size                       2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
